# This is a basic workflow to help you get started with Actions

name: Automate
on: workflow_dispatch

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: create dir
        run: |
         mkdir testResults

      # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"


      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          npm install -g newman-reporter-slackreporter

      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          newman run Books.postman_collection.json -e Book-env.postman_environment.json -r cli,htmlextra --reporter-htmlextra-export testResults/htmlreport.html

      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v3
        with:
          name: RunReports
          path: testResults
